USE MASTER IF EXISTS(SELECT * FROM SYS.databases WHERE NAME = 'BDtcc')
DROP DATABASE BDtcc
GO

CREATE DATABASE BDtcc
GO

USE Bdtcc
GO

CREATE TABLE CLIENTE(
	ID INT IDENTITY PRIMARY KEY,
	Nome VARCHAR (30) NOT NULL,
	Email VARCHAR (100) NOT NULL,
	DataDeNasc DATE NOT NULL,
	Cpf VARCHAR (11) NOT NULL, 
	Logradouro VARCHAR (30) NOT NULL,
	Cep VARCHAR (8) NOT NULL,
	Cidade VARCHAR (20) NOT NULL,
	Bairro VARCHAR (20) NOT NULL,
	UF VARCHAR (2) NOT NULL,
	Complemento VARCHAR (40) NOT NULL
)

GO

CREATE TABLE CONTATO(
	ID INT IDENTITY PRIMARY KEY,
	NUMEROTELE VARCHAR (25)  NOT NULL,
	EMAIL VARCHAR (60) NOT NULL,
	TELEFONEFIXO VARCHAR (11) NULL,
	CLIENTE_ID INT NOT NULL,

	FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)
)

GO

CREATE TABLE CARGO(
	ID INT IDENTITY PRIMARY KEY,
	NomeCargo VARCHAR (40) NOT NULL

)
GO

CREATE TABLE FUNCIONARIO(
	ID INT IDENTITY PRIMARY KEY,
	Nome VARCHAR (50) NOT NULL,
	EMAIL VARCHAR (100) NOT NULL,
	DataDeNasc DATE NULL,
	Cpf VARCHAR (11)  NULL,
	Logradouro VARCHAR (30)  NULL,
	Cep VARCHAR (8) NULL,
	Cidade VARCHAR (20) NULL,
	Bairro VARCHAR (25) NULL,
	UF VARCHAR (2) NULL,
	Complemento VARCHAR ( 40) NULL,
	CARGO_ID INT  NULL,

	FOREIGN KEY (CARGO_ID) REFERENCES CARGO (ID)
)
GO
	
CREATE TABLE ORDEMDESERVIÇO(
	ID INT IDENTITY PRIMARY KEY,
	NomeDeServiço VARCHAR (20) NOT NULL,
	ValorDoServiço INT NOT NULL,
	FUNCIONARIO_ID INT NOT NULL,

	FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO (ID)

)
GO

CREATE TABLE AGENDA(
	ID INT IDENTITY PRIMARY KEY,
	SERVIÇO_ID INT NOT NULL,
	CLIENTE_ID INT NOT NULL,
	DataDeEmissão DATE NOT NULL,
	DescriçãoDoProblema VARCHAR (500) NOT NULL,

	FOREIGN KEY (SERVIÇO_ID) REFERENCES ORDEMDESERVIÇO (ID),
	FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)
)
GO

CREATE TABLE FORMAPAGAMENTO(
	ID INT IDENTITY PRIMARY KEY,
	NomeDoPagemento VARCHAR (20) NOT NULL
	
)
GO

CREATE TABLE PAGAMENTOSERVIÇO(
	ID INT IDENTITY PRIMARY KEY,
	FORMAPAGAMENTO_ID INT NOT NULL,
	AGENDA_ID INT NOT NULL,

	FOREIGN KEY (FORMAPAGAMENTO_ID) REFERENCES FORMAPAGAMENTO (ID),
	FOREIGN KEY (AGENDA_ID) REFERENCES AGENDA (ID)
)
GO

CREATE TABLE CHAT(
	ID INT IDENTITY PRIMARY KEY,
	FUNCIONARIO_ID INT NOT NULL,
	CLIENTE_ID INT NOT NULL,

	FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO (ID),
	FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)
)
GO

CREATE TABLE CONVERSAS(
	ID INT IDENTITY  PRIMARY KEY,
	CHAT_ID INT NOT NULL,

	FOREIGN KEY (CHAT_ID) REFERENCES CHAT (ID)
)


ALTER TABLE FUNCIONARIO ALTER COLUMN EMAIL VARCHAR (110) NULL

