USE MASTER IF EXISTS(SELECT * FROM SYS.databases WHERE NAME = 'BDtcc')

DROP DATABASE BDtcc

GO

CREATE DATABASE BDtcc
go

USE Bdtcc
GO

CREATE TABLE CLIENTE(
	ID INT IDENTITY PRIMARY KEY,
	Nome VARCHAR (30) NOT NULL,
	Email VARCHAR (100) NOT NULL,
	SENHA INT  NULL,
	data_de_nasc DATE NOT NULL,
	Cpf VARCHAR (11) NOT NULL, 
	Logradouro VARCHAR (30) NOT NULL,
	Cep VARCHAR (8) NOT NULL,
	Cidade VARCHAR (20) NOT NULL,
	Bairro VARCHAR (20) NOT NULL,
	UF VARCHAR (2) NOT NULL,
	Complemento VARCHAR (40) NOT NULL
)

GO

CREATE TABLE CONTATO(
	ID INT IDENTITY PRIMARY KEY,
	NUMEROTELE VARCHAR (25)  NOT NULL,
	EMAIL VARCHAR (60) NOT NULL,
	TELEFONEFIXO VARCHAR (11) NULL,
	CLIENTE_ID INT NOT NULL,

	FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)
)

GO

CREATE TABLE CARGO(
	ID INT IDENTITY PRIMARY KEY,
	NomeCargo VARCHAR (40) NOT NULL

)
GO

CREATE TABLE FUNCIONARIO(
	ID INT IDENTITY PRIMARY KEY,
	Nome VARCHAR (50) NOT NULL,
	EMAIL VARCHAR (100) NOT NULL,
	SENHA INT  NULL,
	data_de_nasc DATE NULL,
	Cpf VARCHAR (11)  NULL,
	Logradouro VARCHAR (30)  NULL,
	Cep VARCHAR (8) NULL,
	Cidade VARCHAR (20) NULL,
	Bairro VARCHAR (25) NULL,
	UF VARCHAR (2) NULL,
	Complemento VARCHAR ( 40) NULL,
	CARGO_ID INT  NULL,

	FOREIGN KEY (CARGO_ID) REFERENCES CARGO (ID)
)
GO

CREATE TABLE Imagens (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    imagem VARBINARY(MAX)
)
CREATE TABLE SERVICO(
	ID INT IDENTITY PRIMARY KEY,
	NomeDeServiço VARCHAR (20) NOT NULL,
	DescriçãoDoProblema VARCHAR (500) NOT NULL,
	ValorDoServiço INT  NULL,
	DataDeEmissao DATE NOT NULL,
	DataDeFinalizacao DATE  NULL,
	FUNCIONARIO_ID INT NOT NULL,
	Cliente_ID INT NOT NULL,
	Imagens_ID INT null,
	

	FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO (ID),
	FOREIGN KEY (Cliente_ID) REFERENCES CLIENTE(ID),
	FOREIGN KEY (Imagens_ID) REFERENCES Imagens(ID)
)




CREATE TABLE FORMAPAGAMENTO(
	ID INT IDENTITY PRIMARY KEY,
	NomeDoPagemento VARCHAR (20) NOT NULL
	
)
GO

CREATE TABLE PAGAMENTOSERVIÇO(
	ID INT IDENTITY PRIMARY KEY,
	FORMAPAGAMENTO_ID INT NOT NULL,
	AGENDA_ID INT NOT NULL,

	FOREIGN KEY (FORMAPAGAMENTO_ID) REFERENCES FORMAPAGAMENTO (ID),
	FOREIGN KEY (AGENDA_ID) REFERENCES AGENDA (ID)
)
GO

Select * FROM CLIENTE

Select * FROM ORDEMDESERVICO
Select * FROM FUNCIONARIO
Select * FROM Imagens


ALTER TABLE FUNCIONARIO ALTER COLUMN EMAIL VARCHAR (125) NULL

ALTER TABLE FUNCIONARIO ADD  SENHA INT  NULL

ALTER TABLE OD ADD  SENHA INT  NULL

DROP table ORDEMDESERVIÇO

DELETE FROM FUNCIONARIO 
WHERE ID = 12; 

ADD SENHA INT  NULL

INSERT INTO CARGO(NomeCargo) Values ('Adiministrador')
INSERT INTO CARGO(NomeCargo) Values ('Funcionario')

DBCC CHECKIDENT (FUNCIONARIO, RESEED, 0)

	
